name: release

on:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - '**.go'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # - name: login to ghcr.io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Git Config for Unit Tests
        run: |
          git config --global user.email ci
          git config --global user.name ci
          git config --global init.defaultBranch main

      - name: Run Unit Tests
        run: |
          make test

      - name: Build binary
        run: |
          make build
          chmod +x ./autotag/autotag

      - name: Autotag Merge Commit
        # TODO: replace this with GitHub Action after #41
        run: |
          ./autotag/autotag

          echo "tags:" && git tag -l

      - name: Install rpm
        run: |
          sudo apt-get -qqy update && sudo apt-get -qqy install rpm

      - name: Deploy Autotag Release
        # TODO(vtopc): switch to the `goreleaser/goreleaser-action` GHA?
        run: |
          curl -sL https://git.io/goreleaser | bash -s -- --parallelism=2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
